# These are supported funding model platforms

github: ruchern-chong
patreon: ruchern_chong
open_collective: ruchern-chong
ko_fi: ruchern_chong
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: ruchern.chong
issuehunt: ruchern-chong
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
