version: 2
jobs:
  lint:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: Install packages
        command: yarn
    - save_cache:
        paths:
        - node_modules/
        key: v1-dependencies-{{ checksum "package.json" }}
    - run:
        name: Run linter
        command: |
          yarn lint

workflows:
  version: 2
  lint:
    jobs:
    - lint
